name: ngcm
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- bokeh=0.11.1=py35_0
- ca-certificates=2016.2.28=0
- cloudpickle=0.2.1=py35_1
- cycler=0.10.0=py35_0
- dask=0.9.0=py35_2
- decorator=4.0.9=py35_0
- entrypoints=0.2.1=py35_0
- freetype=2.6.3=0
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_1
- ipython=4.2.0=py35_1
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter_client=4.2.2=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.21=1
- locket=0.2.0=py35_1
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_1
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.0=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=0
- pandas=0.18.1=np111py35_0
- partd=0.3.3=py35_0
- pexpect=4.1.0=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.1=py35_1
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.4=py35_0
- pyyaml=3.11=py35_1
- pyzmq=15.2.0=py35_1
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=21.2.1=py35_0
- simplegeneric=0.8.1=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.6=py35_0
- tk=8.5.19=0
- toolz=0.7.4=py35_0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0

